apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-zagrtfwd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-zagrtfwd 
  name: go-zagrtfwd
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-zagrtfwd 
